# Generated by Django 3.1 on 2020-09-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminderlist', '0016_auto_20200908_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
